### PR TITLE
#32: File constraints now available on both client and server

### PR DESCRIPTION
**Pull request by Pagebakers**
Proposed api and usage: (haven't updated the docs yet)

File restrictions, can be configured both on the client and server
```
Slingshot.fileRestrictions("avatar", {
    allowedFileTypes: ["image/png", "image/jpeg", "image/gif"],
    maxSize: 1*0x400*0x400,
    authorize: function () {
        return this.userId;
    }
});
```

The directive
```
Slingshot.createDirective("avatar", Slingshot.S3Storage, {
        key: function (file) {
            return [
                "users",
                this.userId,
                Date.now() + "-avatar." + file.type.split("/")[1]
            ].join("/");
        }
    });
```

The uploader
```
    uploader = new Slingshot.Upload("avatar");

    var isValid = uploader.validate(file); // true or instance of Error

    uploader.send(...)
```
The validate method is also called right before the authorization request method is called.

### CODE REVIEW

**Comment by josebalius** [comment]
Has this made it to the repo server? The slingshot version I am using doesn't seem to have the `validate` method.

**Comment by gsuess** [comment]
This was released in 0.3.0.

**Comment by josebalius** [comment]
@gsuess I updated to the latest, but validate never returns an error. Is there anyway to debug it further?

**Comment by gsuess** [comment]
The most likely cause is that you have not declared any `fileRestrictions` on the client to validate against.

**Pull request merged**
