### PR TITLE
#22: Allow uploads for Blob.

### LINKED ISSUE #22: support upload of objects other than File
currently I must pass a File object, which is fine if I have an input type=file. What if I try to manipulate an image before uploading? Or try to have the browser generate derivatives for an image and upload those as well? So what if all I have to upload is the dataUrl of a canvas?

### PR DESCRIPTION
**Pull request by gsuess**
Fixes #22.

@jamgold can you please check if this satisfies your use-case?

### CODE REVIEW

**Comment by jamgold** [comment]
when I try to submit the result of canvas.toBlob() it gives me
```
Exception while invoking method 'slingshot/uploadRequest' Error: Match error: Missing key 'name'
```

**Comment by gsuess** [comment]
Sorry about that. Try now. (was assigning a name manually in my tests).

**Comment by jamgold** [comment]
Exception while invoking method 'slingshot/uploadRequest' TypeError: Cannot call method 'split' of undefined

**Comment by jamgold** [comment]
Yes, that was it. My key method used the filename. I changed it to
```
    key: function (file) {
      var ext = file.type.split(/\//).pop();
      var dir = 'slingshot/';
      var fn = Meteor.uuid()+ "." + ext;
      return dir + fn ;
    }
```
and it works.

This is awesome

**Comment by gsuess** [comment]
Great. Thank you for checking it out.

**Pull request merged**
